### ISSUE TITLE
CDN and Plyr examples

### ISSUE THREAD

**Issue by AgentSmith0** [vidstack/examples#21]
What about adding the missing examples for CDN installation and Plyr layout?

**Comment by mihar-22** [comment]
I’ll be adding them today or tomorrow.

**Comment by AgentSmith0** [comment]
@mihar-22 Why don't you want to just add the examples?!??!

**Comment by mihar-22** [comment]
Because I’m busy… please stop this annoying pinging. Everything needed is in the docs.
