### ISSUE TITLE
Adds Slots Example

### ISSUE THREAD

**Issue by Wamy-Dev** [vidstack/examples#37]
Currently having trouble adding slots, so examples would be nice. Something like pipButton, airPlay, etc.

**Comment by mihar-22** [comment]
Not much to it, you can pass in any `ReactNode`:

```tsx
function MyReactComponent() {
  return null;
}

<DefaultVideoLayout slots={{ pipButton: MyReactComponent  }} />
```

If there's something specific you're trying to achieve then you can ask that so I can help further. There's also `before` or `after` (e.g., `beforePipButton` and `afterPipButton`).

**Comment by Wamy-Dev** [comment]
How do we integrate the given buttons as well? Such as the Pipbutton component by vidstack into the slot?

**Comment by mihar-22** [comment]
The button is already included in the layout, the slot will replace it or remove it if set to null. Check out the PIP button component docs on how to use it if you’d like to extend it somehow.
