### ISSUE TITLE
--host option isn't supported

### ISSUE THREAD

**Issue by sedubois** [vidstack/examples#8]
This is what's shown on `pnpm start`:

```
  VITE v4.5.0  ready in 94 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
```

One is led to believe that restarting with `pnpm start --host` would work but it doesn't. Actually one needs (thanks Rahim) to run `pnpm -F wc-tailwind-css dev --host` (to be adapted for the desired example to be run).

**Comment by mihar-22** [comment]
Thanks for the report. I've gone ahead and exposed the network on all examples to help with testing.
